export const REQUEST_PHOTOS = 'REQUEST_PHOTOS';
export const RECEIVE_PHOTOS = 'RECEIVE_PHOTOS';
export const ADD_USER_DATA = 'ADD_USER_DATA';
export const ADD_USER_PHOTO_DATA = 'ADD_USER_PHOTO_DATA';
export const ADD_USER_PAGE_DATA = 'ADD_USER_PAGE_DATA';
export const IS_LOADING = 'IS_LOADING';
